import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Party System",
  description: "Generated by create next app",
  icons: {
    icon: './favicon.ico'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <link rel="icon"
          href="/favicon.ico"
          sizes="any"/>
    <AntdRegistry>{children}</AntdRegistry>
    </body>
    </html>
  );
}
